name: Run Scheduled Task

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: 

jobs:
  run-task:
    runs-on: ubuntu-latest
    steps:
      - name: Call Scheduled Task API
        id: call-task
        run: |
          response=$(curl -s -w "\nHTTP_CODE:%{http_code}" -H "Authorization: Bearer ${{ secrets.SECRET_TOKEN }}" https://your-backend.com/admin/run-scheduled-task)
          echo "Full Response:"
          echo "$response"
          http_code=$(echo "$response" | tail -n1 | sed 's/HTTP_CODE://')
          echo "HTTP Status Code: $http_code"
          
          # Fail if the status code is not 200
          if [ "$http_code" -ne 200 ]; then
            echo "Request failed with status code $http_code"
            exit 1
          fi


